services:
  odoo:
    image: odoo:17.0
    # build: .
    container_name: pm-odoo
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069"
    networks:
      - odoo-network
    volumes:
      - addons:/mnt/extra-addons/addons
      - addition-addons:/mnt/extra-addons/addition-addons
      - odoo-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
    logging:
      options:
        max-size: 10m
    # command: odoo -i project_install --without-demo=WITHOUT_DEMO -d ${POSTGRES_DB} && chown -R odoo:odoo /var/lib/odoo
  db:
    image: postgres:14
    container_name: pm-db
    restart: always
    networks:
      - odoo-network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m
volumes:
  odoo-data:
  db-data:
networks:
  odoo-network:
